### ISSUE TITLE
Names are chopped off on small screens

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2017#17]
![screen shot 2017-03-09 at 6 09 37 pm](https://cloud.githubusercontent.com/assets/105192/23774811/98420d96-04f3-11e7-88a5-f09c35ab8209.png)

**Comment by thomasjbradley** [comment]
Oh, I see, it's because the background colour is dark. It shows up okay on light backgrounds.

Still I think it's a problem…

![screen shot 2017-03-09 at 6 11 14 pm](https://cloud.githubusercontent.com/assets/105192/23774841/ccb83686-04f3-11e7-9b7b-cc4ec9c903a9.png)

**Comment by hellachella** [comment]
I worked hard to chop those suckers off, @thomasjbradley . :)  It's just a style preference. Because full names are present in the email line, the user can still read who the grad is. 

The problem I had with embedding is that I found that the blend modes didn't play nicely once the images were embedded.  I did try changing the z index, but it just broke.  If there is a workaround for that, I would be interested.

**Comment by thomasjbradley** [comment]
Yeah, but their name below with the email link it so tiny and unnoticeable.
It looks really nice on the lighter background, but I don't know how to solve it on the dark bg.

How does it look in browsers that don't support blend mode? When it's just solid?

**Comment by hellachella** [comment]
IE is the only one that doesn't seem to support it nicely.

**Comment by hellachella** [comment]
Fixed layout so that when it's solid everything is ok.  Moved the names down so they are not totally chopped off.  Adjusted the blend modes to not completely disappear.
