### ISSUE TITLE
Social Media Cards

### ISSUE THREAD

**Issue by hellachella** [algonquindesign-grads/2017#24]
Hi @thomasjbradley 

Would you mind doing a quick double check of the social media cards/sitemap?  I want to make sure they are correct.

**Comment by thomasjbradley** [comment]
Looks pretty good. I've got a few small changes:

• I'd probably delete this line:
https://github.com/algonquindesign-grads/2017/blob/master/_layouts/gradlayout.html#L29
Because it's going to show your username when any other designer's are posted to Twitter. Kinda like you taking credit for their work. If it's required maybe put the Studio N Twitter handle.

• Delete this one too, we don't have any embedded Facebook stuff on the page:
https://github.com/algonquindesign-grads/2017/blob/master/_layouts/gradlayout.html#L39

• Should this be the same as `<title>`:
https://github.com/algonquindesign-grads/2017/blob/master/_layouts/gradlayout.html#L20
https://github.com/algonquindesign-grads/2017/blob/master/_layouts/gradlayout.html#L6
Because right now it’s using the reversed names.

• The `meta` is missing in the metadata at the top of `index.html`

• I’d probably ditch the word “Home”, it doesn’t help users any:
https://github.com/algonquindesign-grads/2017/blob/master/index.html#L3

---

Efficiency question: Why duplicate `description` into `meta` when we could just use `{{page.description}}` instead?

**Comment by hellachella** [comment]
We don't have a twitter handle so I didn't know what to put there.  I definitely don't want to take credit for everyone's work.  Removing it.  


Efficiency question: Why duplicate description into meta when we could just use {{page.description}} instead?

When I set up the files, I didn't know we were just going to put the description as the meta. So being a noob, that's what I told Sage to do when she was compiling the .md files.

**Comment by thomasjbradley** [comment]
Alrighty—sounds good to me.
